import { useEffect, useMemo, useState } from 'react';
import { apiPayloadMessage, databaseUrl, jsonHeaders } from '../config/api.js';
import ActionDialog from '../components/ActionDialog.jsx';

const emptyDoctor = { firstName:'', lastName:'', email:'', contactNumber:'', password:'', worksAt:'', speciality:'', licenseNumber:'', emiratesID:'' };
const doctorFieldLimits = { firstName:100, lastName:100, email:254, contactNumber:25, worksAt:255, speciality:100, licenseNumber:100, emiratesID:18 };

export default function Doctors() {
  const [doctors, setDoctors] = useState([]); const [query, setQuery] = useState('');
  const [form, setForm] = useState(emptyDoctor); const [editing, setEditing] = useState(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const [deletingDoctor, setDeletingDoctor] = useState(null);
  const [deactivationImpact,setDeactivationImpact]=useState(null); const [replacementDoctorID,setReplacementDoctorID]=useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = await fetch(databaseUrl('/doctors'), { headers: jsonHeaders() }); const payload = await response.json(); if (!response.ok) throw new Error(apiPayloadMessage(payload,'Unable to load doctors.')); setDoctors(payload.data || []); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  useEffect(()=>{if(!deletingDoctor)return;setDeactivationImpact(null);setReplacementDoctorID('');setSaving(true);fetch(databaseUrl(`/doctors/${encodeURIComponent(deletingDoctor.doctorID)}/deactivation-impact`),{headers:jsonHeaders()}).then(async response=>{const payload=await response.json();if(!response.ok)throw new Error(apiPayloadMessage(payload,'Unable to calculate deactivation impact.'));setDeactivationImpact(payload.data);}).catch(e=>setError(e.message)).finally(()=>setSaving(false));},[deletingDoctor]);
  const visible = useMemo(() => doctors.filter((d) => `${d.firstName} ${d.lastName} ${d.email} ${d.speciality} ${d.licenseNumber} ${d.doctorID}`.toLowerCase().includes(query.toLowerCase())), [doctors, query]);
  const edit = (doctor) => { setEditing(doctor.doctorID); setForm({ ...emptyDoctor, ...doctor, password:'' }); setError(''); setNotice(''); };
  const reset = () => { setEditing(null); setForm(emptyDoctor); };
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); setNotice(''); try { const path = editing ? `/doctors/${encodeURIComponent(editing)}` : '/doctors'; const response = await fetch(databaseUrl(path), { method: editing ? 'PUT' : 'POST', headers: jsonHeaders(), body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) throw new Error(apiPayloadMessage(payload,'Unable to save doctor.')); setNotice(editing ? 'Doctor updated successfully.' : 'Doctor created with an enrolled Fabric identity and is ready for assignment.'); reset(); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const remove = async () => { const doctor = deletingDoctor; if (!doctor||!deactivationImpact) return; if(deactivationImpact.replacementDoctors.length&&!replacementDoctorID){setError('Select a replacement doctor.');return;} setSaving(true); setError(''); setNotice(''); try { const response = await fetch(databaseUrl(`/doctors/${encodeURIComponent(doctor.doctorID)}`), { method:'DELETE', headers:jsonHeaders(),body:JSON.stringify({replacementDoctorID:replacementDoctorID||undefined}) }); const payload = await response.json(); if (!response.ok) throw new Error(apiPayloadMessage(payload,'Unable to deactivate doctor.')); setDeletingDoctor(null); setNotice(payload.message||'Doctor deactivated. Clinical history was preserved.'); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const fields = [['firstName','First name'],['lastName','Last name'],['email','Email'],['contactNumber','Contact number'],['worksAt','Clinic name'],['speciality','Specialty'],['licenseNumber','License number'],['emiratesID','Emirates ID']];
  return <main className="p-8">
    <div className="flex justify-between items-center mb-6"><div><h1 className="text-2xl font-bold">Doctor management</h1><p className="text-gray-600">Clinic-scoped doctor identities and profiles</p></div><input aria-label="Search doctors" className="border rounded px-3 py-2" placeholder="Search doctors" value={query} onChange={(e)=>setQuery(e.target.value)} /></div>
    {error && <div role="alert" className="mb-4 rounded bg-red-100 text-red-800 p-3">{error}</div>}{notice && <div role="status" className="mb-4 rounded bg-green-100 text-green-800 p-3">{notice}</div>}
    <form onSubmit={save} className="bg-white border rounded-xl p-5 mb-6"><h2 className="font-bold mb-3">{editing ? 'Update doctor' : 'Create doctor'}</h2><p className="mb-3 text-sm text-gray-600">Names are limited to 100 characters. Emirates ID must use 784-YYYY-NNNNNNN-C.</p><div className="grid grid-cols-2 gap-3">{fields.map(([name,label])=><label key={name} className="text-sm">{label}<input required maxLength={doctorFieldLimits[name]} pattern={name==='emiratesID'?'784-[0-9]{4}-[0-9]{7}-[0-9]':name==='contactNumber'?'\\+?[0-9][0-9 ()-]{6,24}':name==='licenseNumber'?'[A-Za-z0-9][A-Za-z0-9 ./-]{1,99}':undefined} className="block border rounded px-3 py-2 w-full" value={form[name] || ''} onChange={(e)=>setForm({...form,[name]:e.target.value})} /></label>)}{!editing && <label className="text-sm">Temporary password<input required type="password" minLength={12} maxLength={72} className="block border rounded px-3 py-2 w-full" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})} /></label>}</div><div className="mt-4 flex gap-2"><button disabled={saving} className="bg-blue-700 text-white rounded px-4 py-2 disabled:opacity-60">{saving ? 'Saving…' : editing ? 'Save changes' : 'Create doctor'}</button>{editing && <button type="button" onClick={reset} className="border rounded px-4 py-2">Cancel</button>}</div></form>
    {loading ? <p>Loading doctors…</p> : visible.length === 0 ? <p className="text-gray-600">No doctors found.</p> : <div className="overflow-x-auto bg-white border rounded-xl"><table className="w-full text-left"><thead><tr className="border-b bg-gray-50"><th className="p-3">Doctor</th><th>Specialty</th><th>License</th><th>Contact</th><th>Actions</th></tr></thead><tbody>{visible.map((d)=><tr key={d.doctorID} className="border-b"><td className="p-3"><strong>Dr. {d.firstName} {d.lastName}</strong><div className="text-xs text-gray-500">{d.doctorID}</div></td><td>{d.speciality}</td><td>{d.licenseNumber}</td><td>{d.email}<br/>{d.contactNumber}</td><td><button onClick={()=>edit(d)} className="text-blue-700 mr-4">Edit</button><button onClick={()=>setDeletingDoctor(d)} className="text-red-700">Delete</button></td></tr>)}</tbody></table></div>}
    {deletingDoctor && <ActionDialog title={`Deactivate Dr. ${deletingDoctor.firstName} ${deletingDoctor.lastName}?`} description={deactivationImpact?(deactivationImpact.replacementDoctors.length?`Reassign ${deactivationImpact.assignedPatients.length} patient(s) and ${deactivationImpact.activeAppointments} active appointment(s) to another doctor in this clinic.`:`No other active doctor remains. ${deactivationImpact.activeAppointments} active appointment(s) will be cancelled; clinical history will be preserved.`):'Checking dependent patients and appointments…'} confirmLabel="Deactivate doctor" danger busy={saving} error={error} onClose={() => setDeletingDoctor(null)} onConfirm={remove}>{deactivationImpact?.replacementDoctors.length>0&&<label className="text-sm font-semibold">Replacement doctor<select required value={replacementDoctorID} onChange={e=>setReplacementDoctorID(e.target.value)} className="mt-2 block w-full rounded border p-3"><option value="">Select replacement</option>{deactivationImpact.replacementDoctors.map(doctor=><option key={doctor.doctorID} value={doctor.doctorID}>Dr. {doctor.firstName} {doctor.lastName} — {doctor.speciality}</option>)}</select></label>}</ActionDialog>}
  </main>;
}
