import { useEffect, useMemo, useState } from 'react';
import { databaseUrl, jsonHeaders } from '../config/api.js';

const emptyDoctor = { firstName:'', lastName:'', email:'', contactNumber:'', password:'', worksAt:'', speciality:'', licenseNumber:'', emiratesID:'' };
const errorMessage = (payload, fallback) => payload?.error?.message || payload?.error || fallback;

export default function Doctors() {
  const [doctors, setDoctors] = useState([]); const [query, setQuery] = useState('');
  const [form, setForm] = useState(emptyDoctor); const [editing, setEditing] = useState(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const response = await fetch(databaseUrl('/doctors'), { headers: jsonHeaders() }); const payload = await response.json(); if (!response.ok) throw new Error(errorMessage(payload,'Unable to load doctors')); setDoctors(payload.data || []); } catch (e) { setError(e.message); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const visible = useMemo(() => doctors.filter((d) => `${d.firstName} ${d.lastName} ${d.email} ${d.speciality} ${d.licenseNumber} ${d.doctorID}`.toLowerCase().includes(query.toLowerCase())), [doctors, query]);
  const edit = (doctor) => { setEditing(doctor.doctorID); setForm({ ...emptyDoctor, ...doctor, password:'' }); setError(''); setNotice(''); };
  const reset = () => { setEditing(null); setForm(emptyDoctor); };
  const save = async (event) => { event.preventDefault(); setSaving(true); setError(''); setNotice(''); try { const path = editing ? `/doctors/${encodeURIComponent(editing)}` : '/doctors'; const response = await fetch(databaseUrl(path), { method: editing ? 'PUT' : 'POST', headers: jsonHeaders(), body: JSON.stringify(form) }); const payload = await response.json(); if (!response.ok) throw new Error(errorMessage(payload,'Unable to save doctor')); setNotice(editing ? 'Doctor updated successfully.' : 'Doctor created in MySQL and Fabric. Enroll the new Fabric identity before doctor login.'); reset(); await load(); } catch (e) { setError(e.message); } finally { setSaving(false); } };
  const remove = async (doctor) => { if (!window.confirm(`Delete Dr. ${doctor.firstName} ${doctor.lastName}? This cannot be undone.`)) return; setError(''); setNotice(''); try { const response = await fetch(databaseUrl(`/doctors/${encodeURIComponent(doctor.doctorID)}`), { method:'DELETE', headers:jsonHeaders() }); const payload = await response.json(); if (!response.ok) throw new Error(errorMessage(payload,'Unable to delete doctor')); setNotice('Doctor deleted from MySQL and Fabric. Revoke the Fabric identity during deployment operations.'); await load(); } catch (e) { setError(e.message); } };
  const fields = [['firstName','First name'],['lastName','Last name'],['email','Email'],['contactNumber','Contact number'],['worksAt','Clinic name'],['speciality','Specialty'],['licenseNumber','License number'],['emiratesID','Emirates ID']];
  return <main className="p-8">
    <div className="flex justify-between items-center mb-6"><div><h1 className="text-2xl font-bold">Doctor management</h1><p className="text-gray-600">Clinic-scoped doctor identities and profiles</p></div><input aria-label="Search doctors" className="border rounded px-3 py-2" placeholder="Search doctors" value={query} onChange={(e)=>setQuery(e.target.value)} /></div>
    {error && <div role="alert" className="mb-4 rounded bg-red-100 text-red-800 p-3">{error}</div>}{notice && <div role="status" className="mb-4 rounded bg-green-100 text-green-800 p-3">{notice}</div>}
    <form onSubmit={save} className="bg-white border rounded-xl p-5 mb-6"><h2 className="font-bold mb-3">{editing ? 'Update doctor' : 'Create doctor'}</h2><div className="grid grid-cols-2 gap-3">{fields.map(([name,label])=><label key={name} className="text-sm">{label}<input required className="block border rounded px-3 py-2 w-full" value={form[name] || ''} onChange={(e)=>setForm({...form,[name]:e.target.value})} /></label>)}{!editing && <label className="text-sm">Temporary password<input required type="password" className="block border rounded px-3 py-2 w-full" value={form.password} onChange={(e)=>setForm({...form,password:e.target.value})} /></label>}</div><div className="mt-4 flex gap-2"><button disabled={saving} className="bg-blue-700 text-white rounded px-4 py-2 disabled:opacity-60">{saving ? 'Saving…' : editing ? 'Save changes' : 'Create doctor'}</button>{editing && <button type="button" onClick={reset} className="border rounded px-4 py-2">Cancel</button>}</div></form>
    {loading ? <p>Loading doctors…</p> : visible.length === 0 ? <p className="text-gray-600">No doctors found.</p> : <div className="overflow-x-auto bg-white border rounded-xl"><table className="w-full text-left"><thead><tr className="border-b bg-gray-50"><th className="p-3">Doctor</th><th>Specialty</th><th>License</th><th>Contact</th><th>Actions</th></tr></thead><tbody>{visible.map((d)=><tr key={d.doctorID} className="border-b"><td className="p-3"><strong>Dr. {d.firstName} {d.lastName}</strong><div className="text-xs text-gray-500">{d.doctorID}</div></td><td>{d.speciality}</td><td>{d.licenseNumber}</td><td>{d.email}<br/>{d.contactNumber}</td><td><button onClick={()=>edit(d)} className="text-blue-700 mr-4">Edit</button><button onClick={()=>remove(d)} className="text-red-700">Delete</button></td></tr>)}</tbody></table></div>}
  </main>;
}
