ALTER TABLE Organization
  MODIFY Organization_ID INT NOT NULL AUTO_INCREMENT,
  ADD COLUMN IsActive TINYINT(1) NOT NULL DEFAULT 1 AFTER Type;

ALTER TABLE User
  ADD COLUMN Must_Change_Password TINYINT(1) NOT NULL DEFAULT 0 AFTER IsActive;
